### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by radoslav006** [gamosoft/EndomondoExport#1]
Hi,
I hit the "The request was aborted: Could not create SSL/TLS secure channel" exception during login attempt. I am total noob at C# and networking, but I can say that debugger points to the line:
```c#
using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
```
When I paste url to my web browser it seems like authentication is passing (I get an api auth token).

I will very appreciate any fix or suggestions how to resolve this issue, because I think this is the best endomondo exporter one could find (as it exports also the original endomondo data in *.txt).

Best regards,
Radoslav

**Comment by gamosoft** [comment]
Hi there, I have uploaded a change in the code to fix this, and should upload the binaries to my blog site sometime soon.
Honestly I haven't used this app in years, since I no longer use Endomondo, but it's good to know someone else is using it, thank you!
Here's the latest compiled version in the meantime.
[EndomondoExport.zip](https://github.com/gamosoft/EndomondoExport/files/4982226/EndomondoExport.zip)

**Comment by radoslav006** [comment]
Hi,
I tested it and it works 👍 
Thank you very much for replay, as indeed the previous update to the project was  a quite long time ago.
I was trying to make this by myself using stackoverflow and trial & error technique as I am just embedded C programmer ;) After day of fighting I ended up with some brute force solution that takes app into some-kind-of working, but your solution is for sure better :)
Now I can export (some) of my data, but there is another small problem that can hit some users.. I will post is as separate issue for reference.
